name: Build SGuardLimit Project

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  WDK_VERSION: "10.0.22621.0"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 安装WDK和SDK（纯PowerShell语法）
    - name: Install WDK and SDK
      run: |
        Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=2166289" -OutFile "wdksetup.exe"
        
        Start-Process -Wait -FilePath ".\wdksetup.exe" -ArgumentList @(
          "/quiet",
          "/install",
          "features",
          "+",
          "options.WindowsDriverKitComplete"
        )
        
        $env:WINDOWSSDKDIR = "C:\Program Files (x86)\Windows Kits\10"
        $env:WindowsSdkDir = "C:\Program Files (x86)\Windows Kits\10"
        $env:WindowsSDKVersion = "${{ env.WDK_VERSION }}"
        Add-Content -Path $env:GITHUB_ENV -Value "WINDOWSSDKDIR=$env:WINDOWSSDKDIR"
        Add-Content -Path $env:GITHUB_ENV -Value "WindowsSdkDir=$env:WindowsSdkDir"
        Add-Content -Path $env:GITHUB_ENV -Value "WindowsSDKVersion=$env:WindowsSDKVersion"
      shell: powershell

    # 设置构建环境
    - name: Setup Build Environment
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: 17.0
        windows-sdk-version: ${{ env.WDK_VERSION }}

    # 编译驱动项目
    - name: Build SGuardLimit_VMIO Driver
      run: |
        cd SGuardLimit_VMIO
        
        if exist "x64" rd /s /q x64
        
        msbuild SGuardLimit_VMIO.vcxproj ^
          /p:Configuration=Release ^
          /p:Platform=x64 ^
          /p:WindowsTargetPlatformVersion=%WDK_VERSION% ^
          /p:PlatformToolset=WindowsKernelModeDriver10.0 ^
          /p:AdditionalIncludeDirectories="C:\Program Files (x86)\Windows Kits\10\Include\%WDK_VERSION%\km" ^
          /p:PreprocessorDefinitions="WIN64;_AMD64_;_X86_;NTDDI_VERSION=0x0A000006;WIN32_LEAN_AND_MEAN"
        
        if not exist "x64\Release\Hutao.sys" (
          echo ##[error] Hutao.sys not found!
          dir x64\Release
          exit 1
        )

    # 编译用户层解决方案
    - name: Build sguard_limit Solution
      run: |
        msbuild sguard_limit.sln ^
          /p:Configuration=Release ^
          /p:Platform=x64

    # 上传产物
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sguard_limit_binaries
        path: |
          SGuardLimit_VMIO/x64/Release/Hutao.sys
          x64/Release/*.exe
