name: Build SGuardLimit Project

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # 使用 GitHub 托管的 Windows 运行器

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 使用预装WDK的容器环境
    - name: Build in WDK Container
      uses: windows-actions/run-in-windows-container@v1
      with:
        image: mcr.microsoft.com/windows/servercore:ltsc2022  # 基础镜像
        options: --isolation process  # 进程隔离模式
        setupScript: |
          # 在容器内安装WDK和VS构建工具
          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_buildtools.exe" -OutFile vs_buildtools.exe
          Start-Process -Wait -FilePath .\vs_buildtools.exe -ArgumentList @(
            "--quiet",
            "--norestart",
            "--wait",
            "--add Microsoft.VisualStudio.Workload.VCTools",
            "--add Microsoft.VisualStudio.Component.Windows10SDK.22621"
          )
          
          # 验证安装
          if (-not (Test-Path "C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\km\ntifs.h")) {
            Write-Error "WDK installation verification failed!"
            exit 1
          }
        runScript: |
          # 编译步骤
          cd SGuardLimit_VMIO
          msbuild SGuardLimit_VMIO.vcxproj `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:WindowsTargetPlatformVersion=10.0.22621.0 `
            /p:PlatformToolset=WindowsKernelModeDriver10.0

          cd ..\sguard_limit
          msbuild sguard_limit.sln `
            /p:Configuration=Release `
            /p:Platform=x64

          # 复制产物到主机
          Copy-Item -Path "SGuardLimit_VMIO\x64\Release\Hutao.sys" -Destination "C:\host\"
          Copy-Item -Path "sguard_limit\x64\Release\*.exe" -Destination "C:\host\"
      env:
        GITHUB_WORKSPACE: C:\repo  # 容器内的工作目录

    # 上传产物
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sguard_limit_binaries
        path: |
          Hutao.sys
          *.exe
