name: Build SGuardLimit Project

on: [push, workflow_dispatch]

jobs:
  build: 
    runs-on: windows-latest 

    steps: 
    - name: Checkout code 
      uses: actions/checkout@v2 

    - name: Setup NuGet 
      uses: NuGet/setup-nuget@v1 

    # 步骤5：编译驱动项目
    - name: Build Driver
      shell: powershell
      run: |
        cd SGuardLimit_VMIO
        
        # 使用完整路径调用MSBuild
        & msbuild /t:build SGuardLimit_VMIO.vcxproj `
          /p:Configuration=Release `
          /p:Platform=x64 `
          /p:WindowsTargetPlatformVersion=$env:SDK_VERSION `
          /p:PlatformToolset=WindowsKernelModeDriver10.0 `
          /p:AdditionalIncludeDirectories="C:\Program Files (x86)\Windows Kits\10\Include\$env:WDK_VERSION\km" `
          /p:PreprocessorDefinitions="WIN64;_AMD64_;NTDDI_VERSION=0x0A000006"
        
        if (-not (Test-Path "x64\Release\Hutao.sys")) {
          throw "Driver compilation failed!"
        }

    # 步骤6：编译用户层程序
    - name: Build User Application
      shell: powershell
      run: |
        cd sguard_limit
        & msbuild.exe /t:build sguard_limit.sln `
          /p:Configuration=Release `
          /p:Platform=x64

    # 上传产物
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: |
          SGuardLimit_VMIO/x64/Release/Hutao.sys
          sguard_limit/x64/Release/*.exe
