name: Build SGuardLimit Project

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  WDK_VERSION: "10.0.22621.0"  # 必须与项目实际需要的 WDK 版本一致

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 安装 WDK（静默安装）
    - name: Install WDK
      run: |
        curl.exe -L -o wdksetup.exe https://go.microsoft.com/fwlink/?linkid=2166289
        start /wait wdksetup.exe /quiet /install

    # 配置 MSBuild 环境
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    # 编译驱动项目（关键修复：移除注释行）
    - name: Build SGuardLimit_VMIO Driver
      run: |
        cd SGuardLimit_VMIO
        msbuild SGuardLimit_VMIO.vcxproj ^
          /p:Configuration=Release ^
          /p:Platform=x64 ^
          /p:WindowsTargetPlatformVersion=%WDK_VERSION% ^
          /p:PlatformToolset=WindowsKernelModeDriver10.0 ^
          /p:PreprocessorDefinitions="_AMD64_"

        # 验证输出文件
        if not exist "x64\Release\Hutao.sys" (
          echo ##[error] Hutao.sys not found in x64\Release!
          dir x64\Release
          exit 1
        )

    # 编译用户层解决方案
    - name: Build sguard_limit Solution
      run: |
        msbuild sguard_limit.sln ^
          /p:Configuration=Release ^
          /p:Platform=x64

    # 上传产物
    - name: Upload Artifacts
      uses: actions
