- name: Build in WDK Container
  run: |
    docker run --rm `
      --isolation=process `
      -v ${GITHUB_WORKSPACE}:/repo `
      mcr.microsoft.com/windows/servercore:ltsc2022 powershell -Command "
        # Setup WDK and VS build tools
        Invoke-WebRequest -Uri 'https://aka.ms/vs/17/release/vs_buildtools.exe' -OutFile 'vs_buildtools.exe'
        Start-Process -Wait -FilePath '.\vs_buildtools.exe' -ArgumentList @(
          '--quiet',
          '--norestart',
          '--wait',
          '--add Microsoft.VisualStudio.Workload.VCTools',
          '--add Microsoft.VisualStudio.Component.Windows10SDK.22621'
        )
        if (-not (Test-Path 'C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\km\ntifs.h')) { 
          Write-Error 'WDK installation verification failed!'
          exit 1
        }
        
        # Build steps
        cd 'C:\repo\SGuardLimit_VMIO'
        msbuild 'SGuardLimit_VMIO.vcxproj' `
          /p:Configuration=Release `
          /p:Platform=x64 `
          /p:WindowsTargetPlatformVersion=10.0.22621.0 `
          /p:PlatformToolset=WindowsKernelModeDriver10.0

        cd 'C:\repo\sguard_limit'
        msbuild 'sguard_limit.sln' `
          /p:Configuration=Release `
          /p:Platform=x64

        # Copy artifacts
        Copy-Item -Path 'C:\repo\SGuardLimit_VMIO\x64\Release\Hutao.sys' -Destination 'C:\host\'
        Copy-Item -Path 'C:\repo\sguard_limit\x64\Release\*.exe' -Destination 'C:\host\'
      "
  env:
    GITHUB_WORKSPACE: C:\repo
