name: Build SGuardLimit Project

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  WDK_VERSION: "10.0.22621.0"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 步骤1：安装Visual Studio Build Tools
    - name: Install VS Build Tools
      run: |
        choco install -y visualstudio2022-buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended"
        refreshenv

    # 步骤2：分步安装WDK组件
    - name: Install WDK Components
      run: |
        # 下载WDK安装程序
        Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=2166289" -OutFile wdksetup.exe
        
        # 分步安装必要组件
        Start-Process -Wait -FilePath .\wdksetup.exe -ArgumentList @(
          "/quiet",
          "/norestart",
          "/installpath `"C:\WDK`"",
          "features +",
          "OptionId.WindowsDriverKitComplete",
          "OptionId.WindowsDriverKitVSIntegration"
        )
        
        # 验证安装
        $ntifsPath = "C:\WDK\Include\$env:WDK_VERSION\km\ntifs.h"
        if (-not (Test-Path $ntifsPath)) {
          Write-Error "Critical WDK files missing!"
          Write-Host "Searching for ntifs.h in system..."
          Get-ChildItem "C:\" -Recurse -Filter "ntifs.h" -ErrorAction SilentlyContinue | Select-Object FullName
          exit 1
        }
        
        # 设置环境变量
        echo "WINDOWSSDKDIR=C:\WDK" >> $env:GITHUB_ENV
        echo "WindowsSdkDir=C:\WDK" >> $env:GITHUB_ENV
        echo "WindowsSDKVersion=$env:WDK_VERSION" >> $env:GITHUB_ENV

    # 步骤3：设置完整构建环境
    - name: Setup Build Environment
      run: |
        # 设置完整的包含路径
        $env:INCLUDE = "C:\WDK\Include\$env:WDK_VERSION\km;C:\WDK\Include\$env:WDK_VERSION\shared;$env:INCLUDE"
        $env:LIB = "C:\WDK\Lib\$env:WDK_VERSION\km\x64;$env:LIB"
        
        # 验证环境
        Write-Host "INCLUDE paths: $env:INCLUDE"
        Write-Host "LIB paths: $env:LIB"
        dir "C:\WDK\Include\$env:WDK_VERSION\km\nt*" | Select-Object Name

    # 步骤4：编译驱动项目
    - name: Build SGuardLimit_VMIO Driver
      run: |
        cd SGuardLimit_VMIO
        
        # 强制清理
        if (Test-Path "x64") { Remove-Item -Recurse -Force "x64" }
        
        # 使用完整路径调用msbuild
        & "${env:ProgramFiles}\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\msbuild.exe" SGuardLimit_VMIO.vcxproj `
          /p:Configuration=Release `
          /p:Platform=x64 `
          /p:WindowsTargetPlatformVersion=$env:WDK_VERSION `
          /p:PlatformToolset=WindowsKernelModeDriver10.0 `
          /p:AdditionalIncludeDirectories="C:\WDK\Include\$env:WDK_VERSION\km;C:\WDK\Include\$env:WDK_VERSION\shared" `
          /p:PreprocessorDefinitions="WIN64;_AMD64_;NTDDI_VERSION=0x0A000006"
        
        if (-not (Test-Path "x64\Release\Hutao.sys")) {
          Write-Error "Driver compilation failed!"
          Get-ChildItem -Recurse "x64\Release"
          exit 1
        }

    # 步骤5：编译用户层解决方案
    - name: Build sguard_limit Solution
      run: |
        & "${env:ProgramFiles}\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\msbuild.exe" sguard_limit.sln `
          /p:Configuration=Release `
          /p:Platform=x64

    # 上传产物
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sguard_limit_binaries
        path: |
          SGuardLimit_VMIO/x64/Release/Hutao.sys
          x64/Release/*.exe
