name: Build SGuardLimit Project

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  WDK_VERSION: "10.0.22621.0"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 使用Chocolatey安装完整WDK环境
    - name: Install WDK via Chocolatey
      run: |
        choco install -y windows-driver-kit --version=10.0.22621.0
        refreshenv
      shell: powershell

    # 设置完整的构建环境
    - name: Setup Build Environment
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: 17.0
        windows-sdk-version: ${{ env.WDK_VERSION }}

    # 编译驱动项目 - 终极修复方案
    - name: Build SGuardLimit_VMIO Driver
      run: |
        cd SGuardLimit_VMIO
        
        # 设置完整的WDK环境变量
        set WDK_DIR=C:\Program Files (x86)\Windows Kits\10
        set WDK_VER=%WDK_VERSION%
        set INCLUDE=%WDK_DIR%\Include\%WDK_VER%\km;%WDK_DIR%\Include\%WDK_VER%\shared;%INCLUDE%
        set LIB=%WDK_DIR%\Lib\%WDK_VER%\km\x64;%LIB%
        
        # 强制清理并重建
        if exist "x64" rd /s /q x64
        
        msbuild SGuardLimit_VMIO.vcxproj ^
          /p:Configuration=Release ^
          /p:Platform=x64 ^
          /p:WindowsTargetPlatformVersion=%WDK_VER% ^
          /p:PlatformToolset=WindowsKernelModeDriver10.0 ^
          /p:AdditionalIncludeDirectories="%WDK_DIR%\Include\%WDK_VER%\km;%WDK_DIR%\Include\%WDK_VER%\shared" ^
          /p:PreprocessorDefinitions="WIN64;_AMD64_;NTDDI_VERSION=0x0A000006"
        
        if not exist "x64\Release\Hutao.sys" (
          echo ##[error] Hutao.sys not found!
          echo ##[error] INCLUDE=%INCLUDE%
          dir "%WDK_DIR%\Include\%WDK_VER%\km"
          exit 1
        )

    # 编译用户层解决方案
    - name: Build sguard_limit Solution
      run: |
        msbuild sguard_limit.sln ^
          /p:Configuration=Release ^
          /p:Platform=x64

    # 上传产物
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sguard_limit_binaries
        path: |
          SGuardLimit_VMIO/x64/Release/Hutao.sys
          x64/Release/*.exe
